### PR TITLE
Add line numbers

### PR DESCRIPTION
**Pull request by mjenrungrot**
image

### CODE REVIEW

**Comment by mjenrungrot** [comment]
Not sure about error 
image

**Comment by mjenrungrot** [comment]
The test passed
image

**Comment by jcruz** [comment]
Are you able to change the css selector to not use `classes.output`?

**Comment by mjenrungrot** [comment]
It can, but it may affect the left side as well. Since we don't really care about the background color of the gutter on the left side, I propose the new change in the latest commit.

**Comment by jcruz** [comment]
I'd rather not want `<style jsx>` and rather go with globals in styles
```javascript
'@global': {
  'div > #output > .ace_gutter': {
    background: 'transparent',
  },
},
```

Also 16 font feels a little big, maybe 14 instead?

Edit: actually we can use nesting in styles and add the following to output
```
'& #output > .ace_gutter': {
  background: 'transparent',
},
```

**Comment by mjenrungrot** [comment]
@jcruz  It didn't fix it. Can you try?

**Comment by jcruz** [comment]
Hmm, works for me
screen shot 2018-04-06 at 12 49 12 am
screen shot 2018-04-06 at 12 49 44 am

**Comment by mjenrungrot** [comment]
Done. Put it in the wrong place. Didn't know that you can have it inside.

**Review by jcruz — APPROVED** [review]
LGTM

**Pull request merged**
